// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using expensetracker.Models;

#nullable disable

namespace expensetracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125091530_addBudget")]
    partial class addBudget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("expensetracker.Models.admin", b =>
                {
                    b.Property<int>("adminid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("adminid");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("expensetracker.Models.budget", b =>
                {
                    b.Property<int>("bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("month_year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("bid");

                    b.ToTable("budget");
                });

            modelBuilder.Entity("expensetracker.Models.category", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("cid");

                    b.ToTable("category");
                });

            modelBuilder.Entity("expensetracker.Models.expense", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("eid");

                    b.HasIndex("id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("expensetracker.Models.payment_method", b =>
                {
                    b.Property<int>("pmid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("pmname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pmid");

                    b.ToTable("payment_Method");
                });

            modelBuilder.Entity("expensetracker.Models.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OTP")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OTPGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("bdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("expensetracker.Models.expense", b =>
                {
                    b.HasOne("expensetracker.Models.user", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("expensetracker.Models.user", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
